# Generated by Django 2.2 on 2019-05-17 02:45

from django.db import migrations, models
import formula_one.utils.upload_to
import formula_one.validators.aspect_ratio


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127)),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=formula_one.utils.upload_to.UploadTo('links', 'logos'), validators=[formula_one.validators.aspect_ratio.AspectRatioValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
